{
 "title": "SDK Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Namespace" },
   { "name": "WorkflowType" }
  ]
 },
 "panels": [
  {
   "title": "activities started per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (rate(custom_activity_retries_total{namespace=~\"$Namespace\"}[$__rate_interval]))",
     "legendFormat": "activities started per second"
    }
   ]
  },
  {
   "title": "RespondActivityTaskCompleted / RespondActivityTaskFailed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) ((rate(temporal_request_total{namespace=~\"$Namespace\", operation=~\"RespondActivityTaskCompleted|RespondActivityTaskFailed\" }[$__rate_interval])))",
     "legendFormat": "RespondActivityTaskCompleted or RespondActivityTaskFailed"
    },
    {
     "expr": "sum by (namespace) ((rate(temporal_request_total{namespace=~\"$Namespace\", operation=~\"RespondActivityTaskCompleted\" }[$__rate_interval])))",
     "legendFormat": "RespondActivityTaskCompleted"
    },
    {
     "expr": "sum by (namespace) ((rate(temporal_request_total{namespace=~\"$Namespace\", operation=~\"RespondActivityTaskFailed\" }[$__rate_interval])))",
     "legendFormat": "RespondActivityTaskFailed"
    }
   ]
  },
  {
   "title": "RPC Overview ($Namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Vs Failures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(temporal_request_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(rate(temporal_request_failure_total{namespace=\"$Namespace\"}[5m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "RPC Requests Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) ((rate(temporal_request_total{namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Failures Per Operation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(temporal_request_failure_total{namespace=~\"$Namespace\"}[5m]))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "RPC Latencies ($Namespace)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (namespace, operation, le) (rate(temporal_request_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])))",
     "legendFormat": "{{ namespace }} - {{ operation }}"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Workflow Completion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(temporal_workflow_completed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(temporal_workflow_failed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(temporal_workflow_canceled_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "canceled"
      },
      {
       "expr": "sum(rate(temporal_workflow_continue_as_new_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "continued_as_new"
      }
     ]
    },
    {
     "title": "Workflow End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_endtoend_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Success By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_completed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Failures By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_failed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Workflow Task Throughput By WorkflowType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_task_queue_poll_succeed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Throughput By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_workflow_task_queue_poll_succeed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Empty Polls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_workflow_task_queue_poll_empty_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "Empty Poll - {{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_workflow_task_execution_failed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed  By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, workflow_type) (rate(temporal_workflow_task_execution_failed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, workflow_type, le))",
       "legendFormat": "{{ namespace }} -- {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Activity Throughput By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_activity_execution_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Activity Throughput By Activity Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, activity_type) (rate(temporal_activity_execution_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ activity_type }}"
      }
     ]
    },
    {
     "title": "Failed Activity by Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace, activity_type) (rate(temporal_activity_execution_failed_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }} - {{ activity_type }}"
      }
     ]
    },
    {
     "title": "Activity Execution Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, activity_type, le))",
       "legendFormat": "{{ namespace }} - {{ activity_type }}"
      }
     ]
    },
    {
     "title": "Activity ScheduleToStart",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, activity_type, le))",
       "legendFormat": "{{ namespace }} - {{ activity_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Empty Activity Polls By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_activity_poll_no_task_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_seconds_bucket{namespace=~\"$Namespace\"}[5m])) by (namespace, le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Sticky Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sticky Cache Hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_hit_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_miss_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Forced Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (rate(temporal_sticky_cache_total_forced_eviction_total{namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (temporal_sticky_cache_size)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  }
 ]
}