#!/bin/sh


source ./2-stop-workers.sh


export ACTIONS_PER_SECOND=180
export SLEEP_ACTIVITY_IN_MS=100
export DISABLE_EAGER_DISPATCH=false

export PQL_PORT=8071
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8072
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8073
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8074
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8075
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8076
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8077
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8078
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker

export PQL_PORT=8079
docker run -d -p $PQL_PORT:$PQL_PORT -e PQL_PORT=$PQL_PORT -e ACTIONS_PER_SECOND=$ACTIONS_PER_SECOND \
-e DISABLE_EAGER_DISPATCH=$DISABLE_EAGER_DISPATCH -e SLEEP_ACTIVITY_IN_MS=$SLEEP_ACTIVITY_IN_MS my-metric-worker
